# Generated by Django 4.1.4 on 2022-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='idade'),
        ),
    ]
